apiVersion: epicshelter.crossplane.io/v1
kind: App
metadata:
  namespace: crossplane-system
  name: epicshelter-app
spec:
  parameters:
    clusterName: epicshelter-cluster
    region: eu-central1
    machineType: e2-small
    nodeCount: 1
