apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: epicshelter
  labels:
    app: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:8.1.1-alpine
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          args: [ "valkey-server", "--save", "900", "1", "--dir", "/data" ]
          volumeMounts:
            - name: valkey-data
              mountPath: /data
      volumes:
        - name: valkey-data
          persistentVolumeClaim:
            claimName: valkey-data
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  labels:
    app: valkey
spec:
  selector:
    app: valkey
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP



