apiVersion: apps/v1
kind: Deployment
metadata:
  name: epicshelter
  namespace: epicshelter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: epicshelter
  template:
    metadata:
      labels:
        app: epicshelter
    spec:
      containers:
        - name: epicshelter
          image: b0risdvlpr/epicshelter
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: CACHE_URL
              value: "valkey:6379"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: epicshelter-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: epicshelter
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: epicshelter
spec:
  type: ClusterIP
  selector:
    app: epicshelter
  ports:
    - port: 3000
      targetPort: 3000
