apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-gcp-config
spec:
  projectID: epicshelter-460509
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-secret
      key: creds
