apiVersion: vpc.epicshelter.crossplane.io/v1
kind: App
metadata:
  namespace: crossplane-system
  name: epicshelter-vpc-app
spec:
  parameters:
    region: eu-central-1
    subnet-az-1: eu-central-1a
    subnet-az-2: eu-central-1b
