apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-epicshelter-infra-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/borisdvlpr/epicshelter
    targetRevision: HEAD
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: epicshelter
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true