apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-data
  namespace: epicshelter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
