apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  namespace: crossplane-system
  name: epicshelter-eks-cluster
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: epicshelter-eks-cluster-policy
spec:
  forProvider:
    role: epicshelter-eks-cluster
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
